name: CI

on:
  push:
    branches:
      - '**' # matches every branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0

      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: npm run lint

      - name: npm run test
        run: npm run test

      - name: npm run build
        run: npm run build
