name: CI

on:
  push:
    branches:
      - '**' # matches every branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v7

      - name: Install Node.js and npm with mise
        uses: jdx/mise-action@v4

      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: npm run lint

      - name: npm run test
        run: npm run test

      - name: npm run build
        run: npm run build
